# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "Snow country: Woodcuts of the Japanese Winter"
email: "dejp3@cam.ac.uk"
description: >- # this means to ignore newlines until "baseurl:"
  "Japanese artists have long responded to an altered world of frozen forms,
  stilled by a blanket of snow. In woodcuts they used blank paper to convey
  the purifying beauty of snow in a transformed landscape where even
  'the depths of the night became white'."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://snowcountry.fitzmuseum.cam.ac.uk" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: FitzMuseum_UK
github_username:  fitzwilliammuseum
background: "/images/p.313-1941_1_201207_mfj22_dc1.jpg"
collection_url: "https://data.fitzmuseum.cam.ac.uk"
google_analytics: 'G-2R0YLY9DRS'

# Build settings
plugins:
  - jekyll-feed
words_per_minute: 200
# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
  - jekyll-mentions

collections:
   explore:
      output: true

timezone: Europe/London
permalink: pretty
encoding: "utf-8"
read_time: true
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
